controller:
  image:
    repository: kong/kubernetes-ingress-controller
    tag: "3.4"
  proxy:
    enabled: true

  deployment:
    kong:
      enabled: false

  ingressController:
    enabled: true
    env:
      publish_service: kong/kic-gateway-proxy
    gatewayDiscovery:
      enabled: true

  podAnnotations:
    kuma.io/gateway: enabled

gateway:
  image:
    repository: kong/kong-gateway
    tag: "3.4"

  env:
    database: "off"
    role: "traditional"
    status_listen: 0.0.0.0:8100
    proxy_url: ${KONG_MESH_KIC}
    ssl_cert: /etc/secrets/kong-proxy-tls/tls.crt
    ssl_cert_key:  /etc/secrets/kong-proxy-tls/tls.key

  proxy:
    type: NodePort
    http:
      enabled: true
      nodePort: 30080
    tls:
      enabled: true
      nodePort: 30443
    ingress:
      enabled: true
  enterprise:
    enabled: true
    license_secret: kong-enterprise-license
  
  secretVolumes:
    - kong-cluster-cert
    - kong-proxy-tls
  
  readinessProbe:
    httpGet:
      path: "/status"
  
  status:
    enabled: true
    type: ClusterIP

  enabled: true
  deployment:
    kong:
      enabled: true

  ingressController:
    enabled: false