ingressController:
  enabled: false
deployment:
  kong:
    enabled: true
    daemonset: false
  userDefinedVolumes:
  - name: custom-template
    emptyDir: {}

  userDefinedVolumeMounts:
  - name: custom-template
    subPath: "nginx_kong_gui_include.lua"
    mountPath: "/usr/local/share/lua/5.1/kong/templates/nginx_kong_gui_include.lua"
    readOnly: true

  initContainers:
    - name: kong-prestart
      image: kong/kong-gateway:3.4
      command:
        - "/bin/sh"
        - "-c"
        - |
          # Copy the original nginx_kong.lua to shared volume
          cp /usr/local/share/lua/5.1/kong/templates/nginx_kong_gui_include.lua /mnt/emptydir/nginx_kong_gui_include.lua

          # Modify the nginx_kong.lua file
          sed -i \
            -e "s|^\(\s*\)add_header X-Frame-Options 'sameorigin';|# \1add_header X-Frame-Options 'sameorigin';|" \
            -e "s|^\(\s*\)add_header X-Permitted-Cross-Domain-Policies 'master-only';|# \1add_header X-Permitted-Cross-Domain-Policies 'master-only';|" \
            /mnt/emptydir/nginx_kong_gui_include.lua
      volumeMounts:
        - name: custom-template
          mountPath: /mnt/emptydir
image:
  repository: kong/kong-gateway
  tag: "3.4"
env:
  audit_log: "off"
  database: "postgres"
  role: "control_plane"
  cluster_cert: "/etc/secrets/kong-cluster-cert/tls.crt"
  cluster_cert_key: "/etc/secrets/kong-cluster-cert/tls.key"
  status_listen: 0.0.0.0:8100
  password:
    valueFrom:
      secretKeyRef:
        name: kong-enterprise-superuser-password
        key: password
  admin_gui_url: ${KONG_ADMIN_GUI_URL}
  admin_gui_api_url: ${KONG_ADMIN_API_URI}
  admin_gui_ssl_cert:  /etc/secrets/kong-manager-tls/tls.crt
  admin_gui_ssl_cert_key:  /etc/secrets/kong-manager-tls/tls.key
  admin_ssl_cert: /etc/secrets/kong-admin-tls/tls.crt
  admin_ssl_cert_key:  /etc/secrets/kong-admin-tls/tls.key
cluster:
  enabled: true
  tls:
    enabled: true
    servicePort: 8005
    containerPort: 8005
clustertelemetry:
  enabled: true
  tls:
    enabled: true
    servicePort: 8006
    containerPort: 8006
proxy:
  enabled: false
portal:
  enabled: false
portalapi:
  enabled: false
admin:
  enabled: true
  labels:
    enable-metrics: "true"
  type: NodePort
  http:
    enabled: true
    nodePort: 30001
  tls:
    enabled: true
    nodePort: 30501
  ingress:
    enabled: false
enterprise:
  enabled: true
  license_secret: kong-enterprise-license
  rbac:
    enabled: false
  smtp:
    enabled: false
  ingress:
    enabled: false
manager:
  enabled: true
  type: NodePort
  http:
    nodePort: 30002
  tls:
    enabled: true
    nodePort: 30500
  ingress:
    enabled: false
secretVolumes:
  - kong-cluster-cert
  - kong-manager-tls
  - kong-admin-tls
postgresql:
  enabled: true
  auth:
    username: kong
    database: kong
    password: kong
  image:
    tag: 14
  service:
    ports:
      postgersql: "5432"
serviceMonitor:
  enabled: true
  namespace: monitoring
status:
  enabled: true
  type: ClusterIP
