server {
    listen              443 ssl;
    server_name         proxy;
    access_log          /var/log/nginx/access.log;

    ssl_certificate     /etc/nginx/tls/server.crt;
    ssl_certificate_key /etc/nginx/tls/server.key;

    resolver 127.0.0.11 ipv6=off;

    # Kong DP - Proxy
    location / {
        proxy_pass              http://jaeger-collector:16686/;
        proxy_set_header        Host $host;
        proxy_set_header        X-Real-IP $remote_addr;
        proxy_set_header        X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header        X-Forwarded-Proto $scheme;
        proxy_hide_header       X-Frame-Options;
        #add_header Content-Security-Policy "frame-ancestors https://*.strigo.io";
    }
}
