{
 "title": "Kong Konnect Prometheus",
 "description": "Dashboard that graphs metrics exported via Kong Konnect Prometheus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Request Rate",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "short", "label": "Requests/Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_requests_proxy[1m]))",
     "legendFormat": "kong_requests_proxy"
    }
   ]
  },
  {
   "title": "Request Duration - 90th Percentile",
   "type": "graph",
   "gridPos": { "h": 5, "w": 24, "x": 0, "y": 4 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "kong_latency_proxy"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_bucket[1m])) by (le))",
     "legendFormat": "kong_latency_upstream"
    }
   ]
  },
  {
   "title": "Requests By Status",
   "type": "graph",
   "gridPos": { "h": 4, "w": 24, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short", "label": "Requests/Second" }
   ],
   "targets": [
    {
     "expr": "sum(irate(kong_status_code{status_code=~\"[0-9]+\"}[1m])) by (status_code)",
     "legendFormat": "{{status_code}}"
    }
   ]
  },
  {
   "title": "Proxy latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 13 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_latency_proxy_request_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Min Proxy Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 13 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kong_latency_proxy_request_min)"
    }
   ]
  },
  {
   "title": "Max Proxy Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    {
     "expr": "avg(kong_latency_proxy_request_max)"
    }
   ]
  },
  {
   "title": "Upstream latency",
   "type": "graph",
   "gridPos": { "h": 4, "w": 20, "x": 0, "y": 17 },
   "yaxes": [
    { "format": "ms" }
   ],
   "targets": [
    {
     "expr": "histogram_quantile(0.99, sum(rate(kong_latency_upstream_bucket[1m])) by (le))",
     "legendFormat": "p99"
    },
    {
     "expr": "histogram_quantile(0.90, sum(rate(kong_latency_upstream_bucket[1m])) by (le))",
     "legendFormat": "p90"
    },
    {
     "expr": "histogram_quantile(0.50, sum(rate(kong_latency_upstream_bucket[1m])) by (le))",
     "legendFormat": "p50"
    }
   ]
  },
  {
   "title": "Min Upstream Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 17 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(kong_latency_upstream_min)" }
   ]
  },
  {
   "title": "Max Upstream Latency",
   "type": "stat",
   "gridPos": { "h": 2, "w": 4, "x": 20, "y": 19 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "mean" ] } },
   "targets": [
    { "expr": "avg(kong_latency_upstream_max)" }
   ]
  },
  {
   "title": "Shdict Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 21 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    {
     "expr": "avg(kong_shdict_free_space/kong_shdict_capacity) by (shdict)",
     "legendFormat": "{{shdict}}"
    }
   ]
  },
  {
   "title": "Cache Hits and Misses",
   "type": "graph",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 21 },
   "yaxes": [
    { "format": "short", "label": "Count" }
   ],
   "targets": [
    {
     "expr": "sum(kong_cache_datastore_misses_total)",
     "legendFormat": "hits"
    },
    {
     "expr": "sum(kong_cache_datastore_hits_total)",
     "legendFormat": "misses"
    },
    {
     "expr": "kong_cache_datastore_hits_total/(kong_cache_misses_total+kong_cache_datastore_hits_total)",
     "legendFormat": "Hitrate"
    }
   ]
  }
 ]
}