apiVersion: apps/v1
kind: Deployment
metadata:
  name: kongair-customer
spec:
  replicas: 2
  selector:
    matchLabels:
      app: kongair-customer
  template:
    metadata:
      labels:
        app: kongair-customer
    spec:
      containers:
      - name: kongair-customer
        image: ghcr.io/battlebyte/kongair-customer:latest
        ports:
        - containerPort: 8083
---
apiVersion: v1
kind: Service
metadata:
  name: kongair-customer
spec:
  selector:
    app: kongair-customer
  ports:
  - protocol: TCP
    port: 8083
    targetPort: 8083