#!/usr/bin/env bash
# Insomnia Mockbin utility endpoints demonstration.
#
# Generated by: Arash Eftekhari, Kong Education Team, 2026/10/09
#
# Copyright 2026 Kong Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#
# Grouping, titles, and explanations follow the upstream utility docs:
# https://github.com/Kong/insomnia-mockbin/blob/master/docs/api/utility.md
# The request is the command this script actually sends. The response is
# the live output from mockbin.run, not the sample in the docs.
# Uses HTTPie when installed, otherwise curl. Exits if neither is present.
# Linux, macOS, and WSL. Compatible with Bash 3.2.
# Client calls read /dev/null, and HTTPie is passed --ignore-stdin, so a
# `curl | bash` pipe is not consumed or treated as a request body.
set -u

base="${MOCKBIN_BASE:-https://mockbin.run}"

if command -v https >/dev/null 2>&1; then
  client="https"
elif command -v http >/dev/null 2>&1; then
  client="http"
elif command -v curl >/dev/null 2>&1; then
  client="curl"
else
  printf 'warning: neither HTTPie nor curl is installed\n' >&2
  exit 1
fi

printf 'Insomnia Mockbin utility endpoints demonstration\n'
printf 'Host: %s\n' "$base"
printf 'Client: %s\n' "$client"
printf 'This script calls the utility routes and prints each live response.\n'

group() {
  printf '\n======== %s ========\n' "$1"
}

section() {
  printf '\n------ %s ------\n' "$1"
  printf '%s\n\n' "$2"
}

show() {
  printf 'Request:\n'
  printf '+'
  printf ' %s' "$@"
  printf '\n\nResponse:\n'
}

get() {
  url="$1"
  if [ "$client" = curl ]; then
    show curl -sS -D- "$url"
    curl -sS -D- "$url" </dev/null
  else
    show "$client" --ignore-stdin GET "$url"
    "$client" --ignore-stdin GET "$url" </dev/null
  fi
  printf '\n'
}

get_with() {
  url="$1"
  shift
  if [ "$client" = curl ]; then
    args=(-sS -D-)
    while [ $# -gt 0 ]; do
      args+=(-H "$1")
      shift
    done
    show curl "${args[@]}" "$url"
    curl "${args[@]}" "$url" </dev/null
  else
    show "$client" --ignore-stdin GET "$url" "$@"
    "$client" --ignore-stdin GET "$url" "$@" </dev/null
  fi
  printf '\n'
}

post_json() {
  url="$1"
  body="$2"
  if [ "$client" = curl ]; then
    show curl -sS -D- -X POST -H "Content-Type: application/json" -d "$body" "$url"
    curl -sS -D- -X POST -H "Content-Type: application/json" -d "$body" "$url" </dev/null
  else
    show "$client" --ignore-stdin --raw "$body" POST "$url"
    "$client" --ignore-stdin --raw "$body" POST "$url" </dev/null
  fi
  printf '\n'
}

get_noredirect() {
  url="$1"
  if [ "$client" = curl ]; then
    show curl -sS -D- --max-redirs 0 "$url"
    curl -sS -D- --max-redirs 0 "$url" </dev/null
  else
    show "$client" --ignore-stdin --max-redirects=0 GET "$url"
    "$client" --ignore-stdin --max-redirects=0 GET "$url" </dev/null
  fi
  printf '\n'
}

section "Home" "GET /. Returns the service greeting."
get "$base/"

group "Debugging"

section "Echo" "POST /echo. Returns a response with the same body and content type as the request."
post_json "$base/echo" '{"foo":"bar"}'

section "HTTP Request" "Any method /request/:path. Returns the request as a HAR request object, including path, query, headers, and body."
post_json "$base/request/any/path?foo=bar&foo=baz&key=value" '{"foo":"bar"}'

section "HTTP Archive" "Any method /har/:path. Returns the request as a full HAR log. The creator name on this host is mockbin.run."
get "$base/har/any/path?foo=bar"

group "IP"

section "Origin IP" "GET /ip. Returns the origin IP address seen by Mockbin."
get "$base/ip"

group "Status"

section "Custom Status" "GET /status/:code/:reason. Returns the given status code and reason in the status line and body. Reason defaults to OK."
get "$base/status/201"
get "$base/status/418/I%20am%20a%20teapot"

group "Headers"

section "List Request Headers" "GET /headers. Returns every request header and the header-block size."
get_with "$base/headers" "X-Custom-Header: Foo"

section "Single Header Value" "GET /header/:name. Returns the value of the named request header."
get_with "$base/header/x-custom-header" "X-Custom-Header: Foo"

section "Set a response header" "GET /header/:name/:value. Sets that response header and returns the value."
get "$base/header/x-demo/set-by-path"

section "User Agent" "GET /agent. Returns the user-agent."
get "$base/agent"

group "Cookies"

section "List All Cookies" "GET /cookies. Returns the cookies sent by the client."
get_with "$base/cookies" "Cookie: Greet=Hello; World=Universe"

section "Single Cookie Value" "GET /cookie/:name. Documented as returning the named cookie. This build returns false for a cookie sent on the request."
get_with "$base/cookie/Greet" "Cookie: Greet=Hello"

section "Set a cookie" "GET /cookie/:name/:value. Sets that cookie on the response and returns the value."
get "$base/cookie/session/abc123"

group "Redirects"

section "Redirect Status" "GET /redirect/:status. Starts a redirect with that status. The first hop is shown. The client does not follow it."
get_noredirect "$base/redirect/302"

section "Redirect Loop" "GET /redirect/:status/:count. Counts down one hop at a time, then lands on /redirect/:status/0."
get_noredirect "$base/redirect/302/2"

section "Redirect To Url" "GET /redirect/:status/:count?to=:url. The last hop goes to the to value. This host allows mockbin.run, example.com, httpbingo.net, developer.konghq.com, tools.ietf.org, and api.kong-air.com. A same-host target is returned as a path."
get_noredirect "$base/redirect/302/1?to=/status/200"
get_noredirect "$base/redirect/302/1?to=https://example.com"

group "Delay"

section "Delayed Response" "GET /delay/:ms. Returns after a delay in milliseconds. The default is 200."
get "$base/delay/200"

group "Stream"

section "Stream output" "GET /stream/:chunks. Streams a chunked response. The default is 10 chunks, and the limit is 100."
get "$base/stream/3"

group "Compression"

section "Gzip" "GET /gzip. Same greeting as the home route, with the response body compressed."
if [ "$client" = curl ]; then
  show curl -sS -D- --compressed "$base/gzip"
  curl -sS -D- --compressed "$base/gzip" </dev/null
  printf '\n'
else
  get "$base/gzip"
fi
