apiVersion: configuration.konghq.com/v1
kind: KongPlugin
metadata:
  name: openid-connect-httpbin
plugin: openid-connect
config:
  issuer: ${KEYCLOAK_CONFIG_ISSUER}
  issuers_allowed: 
  - ${KEYCLOAK_URL}/auth/realms/kong
  redirect_uri: 
  - ${KEYCLOAK_REDIRECT_URI}
  client_id:
  - kong
  client_secret:
  - ${CLIENT_SECRET}
  ssl_verify: false
  response_mode: form_post
  introspection_check_active: false
