    kuma:
      nameOverride: kong-mesh
      # The default registry and tag to use for all Kuma images
      global:
        image:
          registry: "docker.io/kong"
          tag: "$KONG_MESH_VERSION"
    
      controlPlane:
        image:
          repository: "kuma-cp"
          pullPolicy: IfNotPresent          
    
        # -- Kuma CP log level: one of off,info,debug
        logLevel: "info"
    
        # -- Kuma CP modes: one of standalone,zone,global
        mode: "zone"
    
        # -- (string) Kuma CP zone, if running multizone
        zone: k8s-zone
    
        # -- Only used in zone mode
        kdsGlobalAddress: "grpcs://$STRIGO_RESOURCE_0_DNS:30001"
    
        autoScaling:
          enabled: false
          minReplicas: 1
          maxReplicas: 2
    
        injectorFailurePolicy: "Ignore"
    
        service:
          # -- Service type of the Kuma Control Plane
          type: ClusterIP
    
        defaults:
          # -- Whether or not to skip creating the default Mesh
          skipMeshCreation: false
    
        # TLS for various servers
        tls:
          general:
            # -- Secret that contains tls.crt, key.crt and ca.crt for protecting Kuma in-cluster communication
            secretName: "tls-secret"
            # -- Base64 encoded CA certificate (the same as in controlPlane.tls.general.secret#ca.crt)
            caBundle: $CA_CRT
          apiServer:
            # -- Secret that contains tls.crt, key.crt for protecting Kuma API on HTTPS
            secretName: "tls-secret"
            # -- Secret that contains list of .pem certificates that can access admin endpoints of Kuma API on HTTPS
            clientCertsSecretName: ""
          kdsGlobalServer:
            # -- Secret that contains tls.crt, key.crt for protecting cross cluster communication
            secretName: "tls-secret"
          kdsZoneClient:
            # -- Secret that contains ca.crt which was used to sign KDS Global server. Used for CP verification
            secretName: "tls-secret"
    
        webhooks:
          validator:
            additionalRules: |
              - apiGroups:
                  - kuma.io
                apiVersions:
                  - v1alpha1
                operations:
                  - CREATE
                  - UPDATE
                  - DELETE
                resources:
                  - opapolicies
          ownerReference:
            additionalRules: |
              - apiGroups:
                  - kuma.io
                apiVersions:
                  - v1alpha1
                operations:
                  - CREATE
                resources:
                  - opapolicies
      # Configuration for the kuma dataplane sidecar
      dataPlane:
        image:
          repository: "kuma-dp"
    
        # Configuration for the kuma init phase in the sidecar
        initImage:
          repository: "kuma-init"
    
      ingress:
        enabled: true
        drainTime: 30s
        replicas: 1
        service:
          type: NodePort
          port: 10001
          nodePort: 30004 
        annotations:
           kuma.io/ingress-public-address: $STRIGO_RESOURCE_1_DNS
           kuma.io/ingress-public-port: "30004" 
        nodeSelector:
          kubernetes.io/os: linux
          kubernetes.io/arch: amd64
    
      egress:
        # -- If true, it deploys Egress for cross cluster communication
        enabled: true
        # -- Time for which old listener will still be active as draining
        drainTime: 30s
        # -- Number of replicas of the Egress
        replicas: 1
        service:
          # -- Service type of the Egress
          type: ClusterIP
          # -- (string) Optionally specify IP to be used by cloud provider when configuring load balancer
          port: 10002
          # -- Port on which service is exposed on Node for service of type NodePort
        annotations: { }
        # -- Node Selector for the Egress pods
        nodeSelector:
          kubernetes.io/os: linux
          kubernetes.io/arch: amd64
